// ── Document Generation + Tenant Docs + KB Routes ────────────────────────
import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const PDFDocument = require("pdfkit");
const { Document, Packer, Paragraph, HeadingLevel, TextRun, AlignmentType } = require("docx");
const PptxGenJS = require("pptxgenjs");

const SECRETS_DIR = os.homedir() + "/.secrets";
const DOCGEN_DIR  = "/opt/itechsmart/docgen";
const TDOCS_DIR   = "/opt/itechsmart/tenant-docs";
const BRAIN_API   = "http://127.0.0.1:8221";

[DOCGEN_DIR, TDOCS_DIR].forEach(d => fs.mkdirSync(d, { recursive: true }));

function readSecret(name) {
  const p = path.join(SECRETS_DIR, name);
  if (fs.existsSync(p)) return fs.readFileSync(p, "utf8").trim();
  return process.env[name] || "";
}

async function callAI(systemPrompt, userPrompt, _getSecret) {
  const NGC_URL = "https://integrate.api.nvidia.com/v1/chat/completions";
  const key = (_getSecret && (_getSecret("NGC_API_KEY") || _getSecret("NVIDIA_API_KEY") || _getSecret("NEMOTRON_API_KEY")))
    || process.env.NGC_API_KEY || process.env.NVIDIA_API_KEY;
  if (!key) throw new Error("NGC_API_KEY not found — add it to ~/.secrets/");
  const r = await fetch(NGC_URL, {
    method: "POST",
    headers: {
      "Authorization": "Bearer " + key,
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      model: "nvidia/nemotron-3-nano-30b-a3b",
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt }
      ],
      temperature: 0.4,
      max_tokens: 4096
    })
  });
  if (!r.ok) {
    const errText = await r.text();
    throw new Error("NGC API error " + r.status + ": " + errText.slice(0, 200));
  }
  const data = await r.json();
  return data.choices?.[0]?.message?.content || "";
}

function safeFilename(name) {
  return name.replace(/[^a-zA-Z0-9_\-\.]/g, "_").slice(0, 80);
}

// ── PDF Generator ──────────────────────────────────────────────────────────
function generatePDF(docData, outPath) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 60, size: "LETTER" });
    const stream = fs.createWriteStream(outPath);
    doc.pipe(stream);

    doc.fontSize(22).font("Helvetica-Bold").fillColor("#1e293b")
       .text(docData.title || "Document", { align: "center" });
    if (docData.subtitle) {
      doc.moveDown(0.3).fontSize(12).font("Helvetica").fillColor("#64748b")
         .text(docData.subtitle, { align: "center" });
    }
    doc.moveDown(0.5)
       .moveTo(60, doc.y).lineTo(550, doc.y).strokeColor("#e2e8f0").lineWidth(1).stroke();
    doc.moveDown(0.5);

    if (docData.metadata) {
      const m = docData.metadata;
      doc.fontSize(10).font("Helvetica").fillColor("#64748b");
      if (m.author)  doc.text(`Author: ${m.author}`);
      if (m.version) doc.text(`Version: ${m.version}`);
      doc.moveDown(0.5);
    }

    for (const section of (docData.sections || [])) {
      doc.moveDown(0.8).fontSize(14).font("Helvetica-Bold").fillColor("#1e40af")
         .text(section.heading || "");
      doc.moveDown(0.3).fontSize(11).font("Helvetica").fillColor("#1e293b");
      for (const line of ((section.content || "")).split("\n")) {
        const t = line.trim();
        if (t.startsWith("- ") || t.startsWith("* ")) {
          doc.text(`  • ${t.slice(2)}`, { indent: 15 });
        } else if (t) {
          doc.text(t);
        } else {
          doc.moveDown(0.2);
        }
      }
    }

    doc.moveDown(2).fontSize(9).fillColor("#94a3b8")
       .text("Generated by iTechSmart AI  ·  iTechSmart Inc.  ·  SDVOSB  ·  CAGE 172W2", { align: "center" });
    doc.end();
    stream.on("finish", resolve);
    stream.on("error", reject);
  });
}

// ── DOCX Generator ─────────────────────────────────────────────────────────
async function generateDOCX(docData, outPath) {
  const children = [];
  children.push(new Paragraph({
    text: docData.title || "Document",
    heading: HeadingLevel.TITLE,
    alignment: AlignmentType.CENTER
  }));
  if (docData.subtitle) {
    children.push(new Paragraph({
      children: [new TextRun({ text: docData.subtitle, color: "64748B", size: 24 })],
      alignment: AlignmentType.CENTER
    }));
  }
  const m = docData.metadata || {};
  if (m.author) children.push(new Paragraph({ children: [new TextRun({ text: `Author: ${m.author}`, color: "64748B", size: 20 })] }));
  if (m.version)children.push(new Paragraph({ children: [new TextRun({ text: `Version: ${m.version}`, color: "64748B", size: 20 })] }));
  children.push(new Paragraph({ text: "" }));

  for (const section of (docData.sections || [])) {
    children.push(new Paragraph({ text: section.heading || "", heading: HeadingLevel.HEADING_1 }));
    for (const line of ((section.content || "")).split("\n")) {
      const t = line.trim();
      if (t.startsWith("- ") || t.startsWith("* ")) {
        children.push(new Paragraph({ text: t.slice(2), bullet: { level: 0 } }));
      } else if (t) {
        children.push(new Paragraph({ text: t }));
      }
    }
    children.push(new Paragraph({ text: "" }));
  }
  children.push(new Paragraph({
    children: [new TextRun({ text: "Generated by iTechSmart AI  ·  SDVOSB  ·  CAGE 172W2", color: "94A3B8", size: 18 })]
  }));

  const document = new Document({ sections: [{ properties: {}, children }] });
  const buf = await Packer.toBuffer(document);
  fs.writeFileSync(outPath, buf);
}

// ── PPTX Generator ─────────────────────────────────────────────────────────
async function generatePPTX(docData, outPath) {
  const pptx = new PptxGenJS();
  pptx.layout = "LAYOUT_WIDE";
  pptx.author = "iTechSmart AI";
  pptx.company = "iTechSmart Inc.";

  const titleSlide = pptx.addSlide();
  titleSlide.background = { color: "0F172A" };
  titleSlide.addText(docData.title || "Presentation", {
    x: 0.5, y: 1.8, w: 12, h: 1.5, fontSize: 36, bold: true, color: "FFFFFF", align: "center"
  });
  if (docData.subtitle) {
    titleSlide.addText(docData.subtitle, { x: 0.5, y: 3.4, w: 12, h: 0.8, fontSize: 20, color: "94A3B8", align: "center" });
  }
  titleSlide.addText("iTechSmart Inc.  ·  SDVOSB  ·  CAGE 172W2", {
    x: 0.5, y: 6.5, w: 12, h: 0.4, fontSize: 10, color: "475569", align: "center"
  });

  for (const section of (docData.sections || [])) {
    const slide = pptx.addSlide();
    slide.background = { color: "1E293B" };
    slide.addText(section.heading || "", {
      x: 0.5, y: 0.4, w: 12, h: 0.8, fontSize: 24, bold: true, color: "3B82F6"
    });
    const lines = ((section.content || "")).split("\n").filter(l => l.trim());
    if (lines.length) {
      const bullets = lines.map(l => {
        const t = l.trim();
        const isBullet = t.startsWith("- ") || t.startsWith("* ");
        return {
          text: isBullet ? t.slice(2) : t,
          options: { bullet: isBullet, fontSize: 15, color: "E2E8F0", breakLine: true }
        };
      });
      slide.addText(bullets, { x: 0.5, y: 1.4, w: 12, h: 5, valign: "top" });
    }
    slide.addText("iTechSmart AI", { x: 0, y: 7.0, w: 13, h: 0.3, fontSize: 8, color: "475569", align: "right" });
  }

  await pptx.writeFile({ fileName: outPath });
}

// ── Route Registration ──────────────────────────────────────────────────────
export function registerDocgenRoutes(app, getSecret) {

  // Generate document from AI prompt
  app.post("/api/docgen/generate", async (req, res) => {
    try {
      const { prompt, format = "pdf", docType = "document", title: userTitle } = req.body || {};
      if (!prompt) return res.status(400).json({ error: "prompt required" });

      const today = new Date().toLocaleDateString("en-US", { month: "long", year: "numeric" });
      const systemPrompt = `You are an expert technical writer for iTechSmart Inc., a SDVOSB UAIO company.
Generate professional ${docType} documents. Respond ONLY with valid JSON matching this schema exactly:
{
  "title": "string",
  "subtitle": "string or null",
  "metadata": { "date": "", "author": "DJuane Jackson, CEO", "version": "1.0" },
  "sections": [
    { "heading": "string", "content": "body text — use '- ' prefix for bullet points on new lines" }
  ]
}
Include 5-8 well-structured sections. Be specific, professional, and thorough.`;

      const raw = await callAI(systemPrompt, `Create a ${docType} for: ${prompt}`, getSecret);

      let docData;
      try {
        const match = raw.match(/\{[\s\S]*\}/);
        docData = JSON.parse(match ? match[0] : raw);
      } catch {
        return res.status(500).json({ error: "AI returned invalid JSON", raw: raw.slice(0, 300) });
      }

      if (userTitle) docData.title = userTitle;

      const ts = Date.now();
      const ext = format === "docx" ? "docx" : format === "pptx" ? "pptx" : "pdf";
      const baseName = safeFilename(docData.title || "document") + "_" + ts;
      const outPath = path.join(DOCGEN_DIR, `${baseName}.${ext}`);

      if (format === "docx") {
        await generateDOCX(docData, outPath);
      } else if (format === "pptx") {
        await generatePPTX(docData, outPath);
      } else {
        await generatePDF(docData, outPath);
      }

      res.json({ ok: true, filename: `${baseName}.${ext}`, title: docData.title, sections: docData.sections?.length || 0, format, docData });
    } catch (e) {
      console.error("[docgen] error:", e.message);
      res.status(500).json({ error: e.message });
    }
  });

  // Download generated doc
  app.get("/api/docgen/download/:filename", (req, res) => {
    const filename = path.basename(req.params.filename);
    const filePath = path.join(DOCGEN_DIR, filename);
    if (!fs.existsSync(filePath)) return res.status(404).json({ error: "File not found" });
    const ext = path.extname(filename).slice(1).toLowerCase();
    const mimeMap = {
      pdf: "application/pdf",
      docx: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      pptx: "application/vnd.openxmlformats-officedocument.presentationml.presentation"
    };
    res.setHeader("Content-Type", mimeMap[ext] || "application/octet-stream");
    res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);
    fs.createReadStream(filePath).pipe(res);
  });

  // List recent generated docs
  app.get("/api/docgen/list", (req, res) => {
    try {
      const files = fs.readdirSync(DOCGEN_DIR)
        .filter(f => /\.(pdf|docx|pptx)$/.test(f))
        .map(f => {
          const stat = fs.statSync(path.join(DOCGEN_DIR, f));
          return { filename: f, size: stat.size, created: stat.mtimeMs };
        })
        .sort((a, b) => b.created - a.created)
        .slice(0, 50);
      res.json({ files });
    } catch { res.json({ files: [] }); }
  });

  // ── TENANT DOCUMENT STORAGE ──────────────────────────────────────────────

  app.post("/api/tenant-docs/:tenantId/init", (req, res) => {
    const dir = path.join(TDOCS_DIR, path.basename(req.params.tenantId));
    fs.mkdirSync(dir, { recursive: true });
    res.json({ ok: true, path: dir });
  });

  app.get("/api/tenant-docs/:tenantId/files", (req, res) => {
    const dir = path.join(TDOCS_DIR, path.basename(req.params.tenantId));
    if (!fs.existsSync(dir)) { fs.mkdirSync(dir, { recursive: true }); return res.json({ files: [] }); }
    const files = fs.readdirSync(dir)
      .filter(f => !f.startsWith("."))
      .map(f => {
        const stat = fs.statSync(path.join(dir, f));
        return { filename: f, size: stat.size, created: stat.mtimeMs, ext: path.extname(f).slice(1) };
      })
      .sort((a, b) => b.created - a.created);
    res.json({ files });
  });

  app.post("/api/tenant-docs/:tenantId/upload", (req, res) => {
    const dir = path.join(TDOCS_DIR, path.basename(req.params.tenantId));
    fs.mkdirSync(dir, { recursive: true });
    const rawName = req.headers["x-filename"] || `upload_${Date.now()}`;
    const filename = safeFilename(decodeURIComponent(rawName));
    const outPath = path.join(dir, filename);
    const stream = fs.createWriteStream(outPath);
    req.pipe(stream);
    stream.on("finish", () => res.json({ ok: true, filename }));
    stream.on("error", e => res.status(500).json({ error: e.message }));
  });

  app.get("/api/tenant-docs/:tenantId/download/:filename", (req, res) => {
    const tenantId = path.basename(req.params.tenantId);
    const filename = path.basename(req.params.filename);
    const filePath = path.join(TDOCS_DIR, tenantId, filename);
    if (!fs.existsSync(filePath)) return res.status(404).json({ error: "File not found" });
    res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);
    fs.createReadStream(filePath).pipe(res);
  });

  app.delete("/api/tenant-docs/:tenantId/:filename", (req, res) => {
    const fp = path.join(TDOCS_DIR, path.basename(req.params.tenantId), path.basename(req.params.filename));
    if (fs.existsSync(fp)) fs.unlinkSync(fp);
    res.json({ ok: true });
  });

  app.get("/api/tenant-docs", (req, res) => {
    if (!fs.existsSync(TDOCS_DIR)) return res.json({ tenants: [] });
    const tenants = fs.readdirSync(TDOCS_DIR)
      .filter(f => fs.statSync(path.join(TDOCS_DIR, f)).isDirectory())
      .map(f => {
        const files = fs.readdirSync(path.join(TDOCS_DIR, f)).filter(x => !x.startsWith("."));
        return { tenantId: f, fileCount: files.length };
      });
    res.json({ tenants });
  });

  // ── KNOWLEDGE BASE (Brain wiki proxy) ────────────────────────────────────

  app.get("/api/kb/articles", async (req, res) => {
    try {
      const r = await fetch(`${BRAIN_API}/api/brain/wiki/articles`, { signal: AbortSignal.timeout(8000) });
      const arr = await r.json();
      const articles = (Array.isArray(arr) ? arr : []).map(a => ({
        ...a,
        tags: (() => {
          if (!a.tags) return [];
          if (Array.isArray(a.tags)) return a.tags;
          if (typeof a.tags !== "string") return [];
          try { return JSON.parse(a.tags); } catch { return []; }
        })()
      }));
      res.json({ articles });
    } catch (e) { res.status(502).json({ error: e.message }); }
  });

  app.get("/api/kb/article/:slug", async (req, res) => {
    try {
      const r = await fetch(`${BRAIN_API}/api/brain/wiki/article/${req.params.slug}`, { signal: AbortSignal.timeout(8000) });
      res.json(await r.json());
    } catch (e) { res.status(502).json({ error: e.message }); }
  });

  app.get("/api/kb/search", async (req, res) => {
    try {
      const q = encodeURIComponent(req.query.q || "");
      const r = await fetch(`${BRAIN_API}/api/brain/search?q=${q}&level=1`, { signal: AbortSignal.timeout(8000) });
      const d = await r.json();
      const raw = d.results || (Array.isArray(d) ? d : []);
      const results = raw.map(a => ({
        ...a,
        tags: (() => {
          if (!a.tags) return [];
          if (Array.isArray(a.tags)) return a.tags;
          if (typeof a.tags !== "string") return [];
          try { return JSON.parse(a.tags); } catch { return []; }
        })()
      }));
      res.json({ results });
    } catch (e) { res.status(502).json({ error: e.message }); }
  });

  console.log("[docgen] routes: /api/docgen/* /api/tenant-docs/* /api/kb/*");
}
